import { test as sharedTest, expect } from '../../shared/multiUser/userAccountFixture';
import { ResolvedUserAccount } from '../../shared/multiUser/types';
import { loginData } from './testData';

/**
 * AmazerTrans's own thin wrapper around the generic, suite-agnostic fixture in
 * e2e/shared/multiUser/userAccountFixture.ts. Re-extends the SAME `userAccount` option fixture
 * with AmazerTrans's own default (derived from the existing single-account `loginData`) instead
 * of the shared module's neutral empty default - this is what lets the untouched `chromium`
 * project (which never sets `userAccount` in its `use` block) keep behaving exactly as it did
 * before multi-user support existed. Every `userN` project generated by buildUserProjects()
 * overrides this default anyway, so this only matters for `chromium`.
 *
 * Kept as its own file (rather than having pricing.spec.ts import the shared module directly) so
 * this suite's login/test code never has to change its import path again if the shared engine
 * evolves.
 */
export const test = sharedTest.extend<{ userAccount: ResolvedUserAccount }>({
  userAccount: [
    {
      id: 'default',
      label: 'DEFAULT',
      username: loginData.username,
      password: loginData.password,
      branch: loginData.branch,
      environment: 'default',
      baseUrl: loginData.url,
      browser: 'chromium',
    },
    { option: true },
  ],
});

export { expect };
export type { ResolvedUserAccount as UserAccount };
